project_name: PhotonSR

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: photonsr
    main: ./cmd/
    binary: photonsr
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  # Opsi rilis umum, kompatibel dengan GoReleaser v1.x
  draft: false
  prerelease: auto # 'auto' akan menandai pre-release jika versi mengandung alpha/beta/rc
  name_template: "{{.ProjectName}} {{.Tag}}" # Judul rilis, misal: PhotonSR v0.2.0

  # Jika Anda sering membuat rilis sebagai draft dan ingin menimpa draft yang ada:
  # replace_existing_draft: true # Hanya berfungsi jika draft: true

  # Konfigurasi spesifik provider
  github:
    owner: arwahdevops
    name: PhotonSR
    # Untuk GoReleaser v1.26.2, 'overwrite' aset untuk rilis yang sudah publish
    # tidak dikonfigurasi secara eksplisit di sini. Jika terjadi konflik aset
    # 'already_exists' pada rilis yang sudah publish, aset perlu dihapus manual
    # di GitHub Releases, atau pertimbangkan update GoReleaser/action ke versi
    # yang mendukung 'overwrite: true' di bawah 'github:'.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'
      - '(?i)skip changelog'
