name: Release PhotonSR

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2' # Sesuaikan dengan versi Go di go.mod Anda

      # Opsional: Uncomment jika Anda build untuk ARM dan membutuhkan QEMU
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # 'version' bisa dikosongkan untuk menggunakan default dari action,
          # atau pin ke versi spesifik GoReleaser jika diperlukan.
          # version: v1.26.2 # Contoh jika ingin pin ke versi yang sama
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }} # Uncomment jika Anda GPG sign rilis
